baseURL = "https://dariagrudzien.com/"
languageCode = "en-us"
title = "Hi, I'm Daria"
theme = "ezhil"

copyright = "© 2020 Daria Grudzien"
googleAnalytics = "UA-165368426-1"
# Number of posts to show in recent posts list (Optional). Defaults to 10.
paginate = 10
# Number of characters to show in summary.
summaryLength = 100
enableEmoji = true
enableRobotsTXT = true

[params]
    subtitle = "I write about tech, comms, and people."
    # Content types which are included in home page recent posts list.
    mainSections = ["posts"]
    # If social media links are enabled then enable this to fetch icons from CDN instead of hosted on your site.
    featherIconsCDN = true
    favicon = "/icons/compass-small.ico"
    customCSS = "/css/custom.css"

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

# Social media links which shows up on site header.
# Uses feather icons for icons. You can [search icon names from here](https://feathericons.com/).
[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/dariagrudzien"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/dariagrudzien"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://linkedin.com/in/dariagru"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

