baseURL = "https://dariagrudzien.com/"
languageCode = "en-us"
title = "Hi, I'm Daria"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

copyright = "Daria Grudzien"
googleAnalytics = "UA-165368426-1"
# Number of characters to show in summary.
summaryLength = 50
enableEmoji = true
enableRobotsTXT = true

[params]
    # description = "I write about tech, comms, and people."
    # Content types which are included in home page recent posts list.
    mainSections = ["posts"]
    favicon = "/icons/favicon.ico"
    custom_css = ["css/custom.css"]
    show_reading_time = true
    site_logo = "/images/dg-w-logo.webp"
    # featured_image = "/images/dg-d-hero.webp"
    recent_posts_number = 5
    twitter = "https://twitter.com/dariagrudzien"
    github = "https://github.com/dariagrudzien"
    linkedin = "https://linkedin.com/in/dariagru"
    rss = "/index.xml"


# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[module]
  [[module.imports]]
    path = "github.com/theNewDynamic/gohugo-theme-ananke"
