baseURL = "https://dariagrudzien.com/"
languageCode = "en-us"
title = "Hello from Daria"
theme = "noteworthy"

googleAnalytics = "UA-165368426-1"

[params]
github = "https://github.com/dariagrudzien"
linkedin = "https://www.linkedin.com/in/dariagru/"
twitter = "https://twitter.com/dariagrudzien"
